### ISSUE TITLE
脚本执行过程中下载内核时出错

### ISSUE THREAD

**Issue by signigelchan** [ophub/flippy-openwrt-actions#6]
**Device Information | 设备信息**
 - SOC: [s905d]
 - Model [Phicomm N1]

**OpenWrt Version | 系统版本**
 - Kernel Version: [5.10.176]
 - Release: [official]

**Describe the bug | 问题描述**

 `Actions` 工作流引入 `ophub/flippy-openwrt-actions@main` ，指定了 `KERNEL_VERSION_NAME` 及 `KERNEL_AUTO_LATEST` ，执行工作流时，发现默认也走了 `RK3588` 的内核下载，导致出错；具体配置如下：

```
- name: Armvirt firmware packit
  uses: ophub/flippy-openwrt-actions@main
  if: steps.compile.outputs.status == 'success' && env.ARMVIRT_PACKIT == 'true' && !cancelled()
  env:
    OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
    KERNEL_REPO_URL: ${{ inputs.packit_kernel_repo }}
    KERNEL_VERSION_NAME: ${{ inputs.packit_kernel_version }}
    KERNEL_AUTO_LATEST: false
    PACKAGE_SOC: ${{ inputs.packit_soc }}
    GZIP_IMGS: .gz
    WHOAMI: ${{ inputs.packit_whoami }}
    OPENWRT_VER: ${{ inputs.packit_owrt_ver }}

- name: Upload packit armvirt firmware
  uses: actions/upload-artifact@v3
  if: > 
    ${{ env.PACKAGED_STATUS }} != '' && ${{ env.PACKAGED_STATUS }} == 'success' &&
    ${{ env.PACKAGED_OUTPUTPATH }} != '' && !cancelled()
  with:
    name: OpenWrt_packit_armvirt${{ env.FILE_DATE }}
    path: ${{ env.PACKAGED_OUTPUTPATH }}/*
```

Please provide a detailed description of the issue and, if necessary, attach a screenshot.

![1](https://github.com/ophub/flippy-openwrt-actions/assets/20301894/f1c937d9-609d-4212-9bc1-904372cd6239)
![2](https://github.com/ophub/flippy-openwrt-actions/assets/20301894/4037e285-2f7b-4a8d-b9c0-3ace44228b8f)
![3](https://github.com/ophub/flippy-openwrt-actions/assets/20301894/a25ad217-922f-46fa-81a2-772ef74da006)
